Model: YOLOv3
Transforms:
- Resize:
    interp: CUBIC
    target_size: 480
- Normalize:
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
TransformsMode: RGB
_Attributes:
  eval_metrics:
    bbox_map: 65.76389368878485
  fixed_input_shape:
  - 480
  - 480
  labels:
  - rebar
  model_type: detector
  num_classes: 1
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  - - im_size
    - im_size
  test_outputs:
  - - bbox
    - multiclass_nms_0.tmp_0
_init_params:
  anchor_masks: null
  anchors: null
  backbone: MobileNetV1
  ignore_threshold: 0.7
  input_channel: 3
  label_smooth: true
  nms_iou_threshold: 0.45
  nms_keep_topk: 100
  nms_score_threshold: 0.01
  nms_topk: 1000
  num_classes: 1
  train_random_shapes:
  - 320
  - 352
  - 384
  - 416
  - 448
  - 480
  - 512
  - 544
  - 576
  - 608
completed_epochs: 0
status: Infer
version: 1.3.11
